services:
  web:
    build: .
    container_name: auth-service
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=ma-super-cle-secrete-partagee-entre-services
      - DJANGO_SETTINGS_MODULE=auth_service.settings
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=auth_service
      - DATABASE_USER=auth_user
      - DATABASE_PASSWORD=auth_pass
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             gunicorn auth_service.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: mysql:8
    container_name: auth-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auth_service
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: