services:
  web:
    build: .
    container_name: post-service
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=ma-super-cle-secrete-partagee-entre-services
      - DJANGO_SETTINGS_MODULE=post_service.settings
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=post_service
      - DATABASE_USER=post_user
      - DATABASE_PASSWORD=post_pass
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             gunicorn post_service.wsgi:application --bind 0.0.0.0:8000"

  db:
    image: mysql:8
    container_name: post-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: post_service
      MYSQL_USER: post_user
      MYSQL_PASSWORD: post_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: